name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.14.0-alpha.3", 3.8, 3.9, "3.10.9"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install deprecation pytest pytest-mock psutil pyflakes && git submodule update --init --recursive
      - name: Run check syntax
        run: ./check_syntax.sh
      - name: Run tests
        run: ./run_uts.sh
